

services:
  namenode:
    build: .
    container_name: namenode
    hostname: namenode
    ports:
      - "9870:9870"  # Web UI
      - "9000:9000"  # HDFS
    volumes:
      - namenode_data:/hadoop/dfs/name
    networks:
      - hadoop-net

  datanode1:
    build: .
    container_name: datanode1
    hostname: datanode1
    volumes:
      - datanode1_data:/hadoop/dfs/data
    networks:
      - hadoop-net

  datanode2:
    build: .
    container_name: datanode2
    hostname: datanode2
    volumes:
      - datanode2_data:/hadoop/dfs/data
    networks:
      - hadoop-net

volumes:
  namenode_data:
  datanode1_data:
  datanode2_data:

networks:
  hadoop-net:
    driver: bridge
